# Generated by Django 4.2.16 on 2025-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_category_alter_choice_votes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Science', 'Science'), ('Health', 'Health'), ('Education', 'Education'), ('Business', 'Business'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Art', 'Art'), ('History', 'History'), ('Culture', 'Culture'), ('Literature', 'Literature'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Personal Development', 'Personal Development'), ('Gaming', 'Gaming'), ('Startups', 'Startups'), ('Economics', 'Economics'), ('Fitness', 'Fitness'), ('Relationships', 'Relationships'), ('Parenting', 'Parenting'), ('DIY & Crafts', 'DIY & Crafts'), ('Movies', 'Movies'), ('TV Shows', 'TV Shows'), ('Music', 'Music'), ('Cryptocurrency', 'Cryptocurrency'), ('AI & Machine Learning', 'AI & Machine Learning'), ('Astronomy', 'Astronomy'), ('Automobiles', 'Automobiles'), ('Mental Health', 'Mental Health'), ('Volunteerism', 'Volunteerism'), ('Career Development', 'Career Development'), ('Hobbies', 'Hobbies'), ('Pets & Animals', 'Pets & Animals'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
