# Generated by Django 4.2.16 on 2025-01-29 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 20, 0, 32, 530242, tzinfo=datetime.timezone.utc)),
        ),
    ]
