# Generated by Django 4.2.16 on 2025-01-30 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 20, 56, 1, 846501, tzinfo=datetime.timezone.utc)),
        ),
    ]
