# Generated by Django 4.2.16 on 2025-01-30 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 21, 11, 4, 119832, tzinfo=datetime.timezone.utc)),
        ),
    ]
