# Generated by Django 4.2.16 on 2025-01-30 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 21, 13, 58, 421818, tzinfo=datetime.timezone.utc)),
        ),
    ]
