# Generated by Django 4.2.16 on 2025-02-01 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 8, 46, 16, 65330, tzinfo=datetime.timezone.utc)),
        ),
    ]
