# Generated by Django 4.2.16 on 2025-02-15 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_poll_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 16, 23, 24, 249312, tzinfo=datetime.timezone.utc)),
        ),
    ]
